name: deploy
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist
